Arena = Arena or {}

Arena.Client = {
    inArena = false,
    inHub = false,
    spectating = false,
    watching = false,
    down = false,
    uiOpen = false,
    loadoutOpen = false,
    ambulanceArena = false,
    lobby = nil,
    map = nil,
    team = 0,
    spawn = nil,
    muteStreaks = false,
    muteSounds = false,
    returnCoords = nil,
    worldReturnCoords = nil,
    frozen = false,
    teamkill = false,
    weaponName = nil,
    weaponSlot = nil,
    invBlocked = false,
    equipRetries = 0,
}
